warning: in the working copy of 'app/(company)/about/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/accessibility/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/accuracy-policy/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/affiliate-disclosure/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/careers/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/contact/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/cookies/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/deal-insights/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/disclaimer/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/editorial-policy/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/faq/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/guides/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/help/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/how-it-works/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/mission/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/privacy/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/report-information/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/suggest-product/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/terms/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/(company)/trademark-notice/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/admin/(protected)/analytics/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/compare/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/knowledge-hub/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/layout.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/products/[slug]/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/sitemap.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app/trending/page.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'components/admin/admin-stat-card.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'components/compare/compare-page-client.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'components/home/home-feature-card.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'components/product/product-gallery.tsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'lib/data/admin-analytics.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'lib/data/public-product.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'lib/data/public-seo.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'lib/seo/site.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tests/seo-domain.test.ts', LF will be replaced by CRLF the next time Git touches it
