import type { Metadata } from "next";
import Link from "next/link";
import { AdminEmptyState } from "@/components/admin/admin-empty-state";
import { BlogDeleteButton } from "@/components/admin/blog-delete-button";
import { getAdminBlogPosts } from "@/lib/data/admin-blog";

export const metadata: Metadata = { title: "Knowledge Hub | HypeBuzz Admin" };
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "Not set";
export default async function AdminBlogPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const [{ posts, hasError }, params] = await Promise.all([getAdminBlogPosts(), searchParams]);
  const notices: Record<string, string> = { created: "Article created successfully.", updated: "Article updated successfully.", deleted: "Article deleted successfully." };
  return <div><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[#2563EB]">Content management</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Knowledge Hub</h1><p className="mt-3 text-base leading-7 text-[#6B7280]">Prepare and manage articles without exposing drafts publicly.</p></div><div className="flex flex-wrap gap-3"><Link className="min-h-11 rounded-[10px] border border-[#D1D5DB] bg-white px-4 py-3 text-sm font-semibold" href="/admin/blog/categories">Categories</Link><Link className="min-h-11 rounded-[10px] border border-[#D1D5DB] bg-white px-4 py-3 text-sm font-semibold" href="/admin/blog/tags">Tags</Link><Link className="min-h-11 rounded-[10px] bg-[#2563EB] px-5 py-3 text-sm font-semibold text-white" href="/admin/blog/new">New article</Link></div></header>
    {params.notice && notices[params.notice] ? <div className="mt-6 rounded-[10px] border border-[#BBF7D0] bg-[#F0FDF4] px-4 py-3 text-sm font-medium text-[#166534]" role="status">{notices[params.notice]}</div> : null}
    {hasError ? <div className="mt-6 rounded-[10px] border border-[#FCA5A5] bg-[#FEF2F2] px-4 py-3 text-sm text-[#991B1B]" role="alert">Articles could not be loaded. Apply the blog migration and check the Supabase connection.</div> : null}
    <section className="mt-8">{posts.length === 0 ? <div className="rounded-2xl border border-[#E5E7EB] bg-white"><AdminEmptyState actionHref="/admin/blog/new" actionLabel="Create article" description="No articles yet. Create your first article when you are ready." title="No articles yet"/></div> : <div className="overflow-x-auto rounded-2xl border border-[#E5E7EB] bg-white"><table className="w-full min-w-[70rem] text-left"><thead className="bg-[#F8FAFC] text-xs uppercase tracking-wide text-[#6B7280]"><tr><th className="px-5 py-3">Title</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Featured</th><th className="px-5 py-3">Published</th><th className="px-5 py-3">Updated</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{posts.map((post) => <tr key={post.id}><th className="px-5 py-4 font-semibold">{post.title}</th><td className="px-5 py-4 text-sm text-[#6B7280]">{post.categoryName ?? "Uncategorized"}</td><td className="px-5 py-4 text-sm capitalize">{post.status}</td><td className="px-5 py-4 text-sm">{post.featured ? "Yes" : "No"}</td><td className="px-5 py-4 text-sm text-[#6B7280]">{date(post.publishedAt)}</td><td className="px-5 py-4 text-sm text-[#6B7280]">{date(post.updatedAt)}</td><td className="px-5 py-4"><div className="flex items-start gap-2"><Link className="min-h-10 rounded-[10px] border border-[#D1D5DB] px-3 py-2 text-sm font-semibold" href={`/admin/blog/${post.id}/edit`}>Edit</Link><BlogDeleteButton id={post.id} title={post.title}/></div></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
