export const productImportExample = {
  productName: "ASIAN Boss-25 Men's Running, Walking & Training Shoes",
  slug: "asian-boss-25-mens-running-walking-training-shoes-off-white-brown",
  brand: "ASIAN",
  category: "Sports Shoes",
  subcategory: "Men's Sports Shoes",
  shortDescription: "Lightweight men's sports shoes with soft cushioning and a flexible sole.",
  description: "A detailed original product description.",
  highlights: ["Lightweight construction", "Soft cushioning", "Flexible sole", "Suitable for running and walking"],
  specifications: { Brand: "ASIAN", Model: "Boss-25", Colour: "Off White Brown", Gender: "Men", Type: "Running Shoes", Closure: "Lace-Up" },
  offers: [
    { merchant: "Amazon", affiliateUrl: "https://link.amazon/example", currentPrice: 899, originalPrice: 1999, currency: "INR", stockStatus: "in_stock", activeOffer: true, offerLabel: "Limited Time Deal" },
    { merchant: "Flipkart", affiliateUrl: "https://www.flipkart.com/example?affid=hypebuzz", currentPrice: 849, originalPrice: 1999, currency: "INR", stockStatus: "in_stock", activeOffer: true },
  ],
  discountPercentage: 55,
  featuredProduct: false,
  trendingProduct: true,
  status: "draft",
  seoTitle: "ASIAN Boss-25 Men's Running Shoes",
  seoDescription: "Discover ASIAN Boss-25 lightweight running shoes with soft cushioning and a flexible sole.",
  searchTags: ["men's running shoes", "walking shoes", "sports shoes", "ASIAN shoes"],
  pros: ["Lightweight", "Comfortable cushioning"],
  considerations: ["Check the size chart before ordering"],
  faq: [{ question: "Are these suitable for walking?", answer: "They are designed for walking, running and training." }],
};
