import Link from "next/link";
import { legalReviewNotice, policyLastUpdated, policyLastUpdatedLabel } from "@/lib/content/policy-constants";
import { CompanyCta } from "@/components/company/company-cta";
import { InformationHero } from "./information-hero";

export type InformationSectionData = { heading: string; paragraphs?: readonly string[]; items?: readonly string[]; links?: readonly { label: string; href: string; description: string }[] };
export type InformationPageData = { eyebrow: string; title: string; introduction: string; sections: readonly InformationSectionData[]; policy?: boolean; status?: string; cta?: { title: string; description: string; secondaryHref?: string; secondaryLabel?: string } };

const focusRing = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2563EB] focus-visible:ring-offset-2";

export function InformationPage({ page }: { page: InformationPageData }) {
  return <><InformationHero eyebrow={page.eyebrow} introduction={page.introduction} title={page.title} updatedDate={page.policy ? policyLastUpdated : undefined} updatedLabel={page.policy ? policyLastUpdatedLabel : undefined} />
    <div className="mx-auto grid max-w-[1280px] gap-10 px-4 py-14 sm:px-6 sm:py-16 lg:grid-cols-[15rem_minmax(0,48rem)] lg:justify-between lg:px-8">
      <aside className="lg:sticky lg:top-40 lg:self-start"><nav aria-label={`${page.title} contents`}><h2 className="text-sm font-bold uppercase tracking-[0.14em] text-[#6B7280]">On this page</h2><ol className="mt-3 space-y-1">{page.sections.map((section, index) => <li key={section.heading}><a className={`inline-flex min-h-11 items-center rounded-md text-sm font-semibold text-[#374151] hover:text-[#1D4ED8] ${focusRing}`} href={`#section-${index + 1}`}>{section.heading}</a></li>)}</ol></nav></aside>
      <article className="min-w-0"><div className="space-y-12">{page.sections.map((section, index) => <section aria-labelledby={`section-${index + 1}`} className="scroll-mt-40" key={section.heading}><h2 className="text-2xl font-bold tracking-tight text-[#111827] sm:text-3xl" id={`section-${index + 1}`}>{section.heading}</h2>{section.paragraphs?.map((paragraph) => <p className="mt-4 text-base leading-7 text-[#4B5563]" key={paragraph}>{paragraph}</p>)}{section.items ? <ul className="mt-5 space-y-3">{section.items.map((item) => <li className="flex gap-3 leading-7 text-[#4B5563]" key={item}><span aria-hidden="true" className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#2563EB]" />{item}</li>)}</ul> : null}{section.links ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{section.links.map((link) => <Link className={`rounded-2xl border border-[#E5E7EB] bg-white p-5 hover:border-[#2563EB] hover:bg-[#EFF6FF] ${focusRing}`} href={link.href} key={link.label}><span className="font-semibold text-[#1D4ED8]">{link.label}</span><span className="mt-2 block text-sm leading-6 text-[#4B5563]">{link.description}</span></Link>)}</div> : null}</section>)}</div>{page.status ? <aside className="mt-12 rounded-2xl border border-[#BFDBFE] bg-[#EFF6FF] p-6" role="status"><h2 className="text-xl font-semibold text-[#111827]">Current availability</h2><p className="mt-2 leading-7 text-[#374151]">{page.status}</p></aside> : null}{page.policy ? <aside className="mt-12 border-l-4 border-[#2563EB] bg-[#F8FAFC] p-5 text-sm leading-6 text-[#4B5563]"><p>{legalReviewNotice}</p></aside> : null}</article>
    </div><CompanyCta description={page.cta?.description ?? "Explore products and available merchant offers, or contact HypeBuzz if you need assistance."} secondaryHref={page.cta?.secondaryHref ?? "/contact"} secondaryLabel={page.cta?.secondaryLabel ?? "Contact HypeBuzz"} title={page.cta?.title ?? "Continue with HypeBuzz"} /></>;
}
