/* eslint-disable @next/next/no-img-element -- Supabase bucket host is deployment-specific. */
import type { Metadata } from "next";
import Link from "next/link";
import { KnowledgeHubActions } from "@/components/admin/knowledge-hub-actions";
import { getAdminGuides } from "@/lib/data/admin-knowledge-hub";
import { KNOWLEDGE_HUB_CATEGORIES } from "@/lib/validation/knowledge-hub";
export const metadata: Metadata = { title: "PDF Guides | HypeBuzz Admin" };
const date = (v: string | null) => v ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(v)) : "—"; const size = (n: number) => `${(n / 1024 / 1024).toFixed(1)} MB`;
export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; category?: string; notice?: string }> }) { const p = await searchParams; const { guides, hasError } = await getAdminGuides(p.q, p.status, p.category); const notices: Record<string,string> = { created: "Guide saved successfully.", updated: "Guide updated successfully.", deleted: "Guide and stored files deleted." }; return <div><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[#2563EB]">Content management</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">PDF Guides</h1><p className="mt-3 text-[#6B7280]">Upload, publish, and manage Knowledge Hub PDFs.</p></div><Link className="inline-flex min-h-12 items-center justify-center rounded-[10px] bg-[#2563EB] px-5 font-semibold text-white" href="/admin/knowledge-hub/new">Upload guide</Link></header>
  {p.notice && notices[p.notice] ? <div className="mt-6 rounded-[10px] border border-[#BBF7D0] bg-[#F0FDF4] px-4 py-3 text-sm font-medium text-[#166534]" role="status">{notices[p.notice]}</div> : null}{hasError ? <div className="mt-6 rounded-[10px] border border-[#FCA5A5] bg-[#FEF2F2] px-4 py-3 text-sm text-[#991B1B]" role="alert">Guides could not be loaded. Apply migration 017 and check Supabase.</div> : null}
  <form className="mt-6 grid gap-3 rounded-xl border border-[#E5E7EB] bg-white p-4 sm:grid-cols-3"><input aria-label="Search guides" className="min-h-12 rounded-[10px] border border-[#D1D5DB] px-4" defaultValue={p.q} name="q" placeholder="Search by title"/><select aria-label="Filter by status" className="min-h-12 rounded-[10px] border border-[#D1D5DB] px-4" defaultValue={p.status} name="status"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option></select><select aria-label="Filter by category" className="min-h-12 rounded-[10px] border border-[#D1D5DB] px-4" defaultValue={p.category} name="category"><option value="">All categories</option>{KNOWLEDGE_HUB_CATEGORIES.map(x => <option key={x}>{x}</option>)}</select><button className="min-h-11 rounded-[10px] bg-[#111827] px-4 font-semibold text-white sm:col-start-3" type="submit">Apply filters</button></form>
  <section className="mt-6 space-y-3">{guides.length === 0 ? <div className="rounded-2xl border border-[#E5E7EB] bg-white p-10 text-center"><h2 className="text-xl font-bold">No guides found</h2><p className="mt-2 text-[#6B7280]">Upload a PDF or adjust the filters.</p></div> : guides.map(g => <article className="grid gap-4 rounded-2xl border border-[#E5E7EB] bg-white p-4 sm:grid-cols-[8rem_1fr] lg:grid-cols-[8rem_1fr_auto]" key={g.id}><div className="aspect-[16/9] overflow-hidden rounded-lg bg-[#E5E7EB]">{g.thumbnail_url ? <img alt="" className="h-full w-full object-cover" src={g.thumbnail_url}/> : <div className="flex h-full items-center justify-center text-xs font-semibold text-[#6B7280]">PDF GUIDE</div>}</div><div className="min-w-0"><h2 className="truncate text-lg font-bold">{g.title}</h2><p className="mt-1 text-sm text-[#6B7280]">{g.category} · <span className="capitalize">{g.status}</span> · {size(g.pdf_size_bytes)}</p><p className="mt-1 text-xs text-[#6B7280]">Uploaded {date(g.created_at)} · Published {date(g.published_at)}</p></div><div className="flex flex-wrap items-center gap-2 sm:col-span-2 lg:col-span-1"><Link className="inline-flex min-h-10 items-center rounded-[10px] border border-[#D1D5DB] px-3 text-sm font-semibold" href={`/admin/knowledge-hub/${g.id}/edit`}>Edit</Link><a className="inline-flex min-h-10 items-center rounded-[10px] border border-[#D1D5DB] px-3 text-sm font-semibold" href={g.pdf_url} rel="noopener noreferrer" target="_blank">Preview</a><KnowledgeHubActions id={g.id} status={g.status} title={g.title}/></div></article>)}</section></div>; }
