import type { Metadata } from "next";
import { CompanyCta } from "@/components/company/company-cta";
import { InformationHero } from "@/components/information/information-hero";
import { UiOnlyForm } from "@/components/information/ui-only-form";
import { supportEmail } from "@/lib/content/policy-constants";
import { absoluteUrl } from "@/lib/seo/site";
const description="Learn how to suggest a product for future HypeBuzz catalogue consideration without implying guaranteed inclusion.";
export const metadata:Metadata={title:"Suggest a Product",description,alternates:{canonical:absoluteUrl("/suggest-product")},openGraph:{type:"website",title:"Suggest a Product | HypeBuzz",description,url:absoluteUrl("/suggest-product"),siteName:"HypeBuzz"},twitter:{card:"summary_large_image",title:"Suggest a Product | HypeBuzz",description}};
const fields=[{id:"product-name",label:"Product name",placeholder:"Full product name"},{id:"brand",label:"Brand",placeholder:"Product brand"},{id:"category",label:"Category",placeholder:"Product category"},{id:"product-url",label:"Product URL",placeholder:"Manufacturer or merchant URL",type:"url" as const},{id:"suggested-merchant",label:"Suggested merchant",placeholder:"Merchant where the product is available"},{id:"reason",label:"Reason for suggestion",placeholder:"Explain why this product could be useful to HypeBuzz users",type:"textarea" as const},{id:"name",label:"Name",placeholder:"Your name",autoComplete:"name"},{id:"email",label:"Email",placeholder:"you@example.com",type:"email" as const,autoComplete:"email"}] as const;
export default function Page(){return <><InformationHero eyebrow="Resources" introduction="Share a product that may merit future catalogue review. Suggestions inform consideration but do not guarantee inclusion, ranking, or endorsement." title="Suggest a Product"/><section className="mx-auto max-w-[960px] px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="rounded-2xl border border-[#E5E7EB] bg-white p-6 sm:p-8"><h2 className="text-2xl font-bold text-[#111827]">Product suggestion</h2><p className="mt-3 leading-7 text-[#4B5563]">HypeBuzz may consider relevance, reliable information, catalogue coverage, user usefulness, and operational capacity. Commission potential should not be the sole reason for inclusion. This form does not currently send or store entries; general enquiries can be emailed to <a className="font-semibold text-[#1D4ED8] underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2563EB]" href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p><div className="mt-8"><UiOnlyForm fields={fields} notice="Product suggestion submission functionality is coming soon."/></div></div></section><CompanyCta description="Browse current product information or learn how HypeBuzz approaches editorial selection." secondaryHref="/editorial-policy" secondaryLabel="Read the editorial policy" title="Continue exploring HypeBuzz"/></>}
