import Image from "next/image";
import Link from "next/link";
import { CompareButton, WishlistButton } from "./product-card-actions";
export type ProductCardProduct = { id: string; name: string; brand: string; imageSrc: string; imageAlt: string; price: number; currency?: string; storeCount: number; productHref: string; dealsHref: string; initiallyWishlisted?: boolean };
const focus = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2563EB] focus-visible:ring-offset-2";
export function ProductCard({ product }: { product: ProductCardProduct }) {
 const price = new Intl.NumberFormat("en-IN", { style: "currency", currency: product.currency ?? "INR", maximumFractionDigits: 0 }).format(product.price);
 return <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg motion-reduce:transform-none">
  <div className="relative aspect-square overflow-hidden bg-[#F8FAFC]"><Link aria-label={`View ${product.name}`} className={`block h-full w-full ${focus}`} href={product.productHref}><Image alt={product.imageAlt} className="object-contain p-6" fill sizes="(max-width: 639px) 100vw, (max-width: 1023px) 50vw, 33vw" src={product.imageSrc} /></Link><span className="absolute left-3 top-3 rounded-md border border-blue-200 bg-[#EFF6FF] px-2 py-1 text-xs font-semibold text-[#1D4ED8]">Best Price</span><div className="absolute right-3 top-3"><WishlistButton initiallyWishlisted={product.initiallyWishlisted} productName={product.name} /></div></div>
  <div className="flex flex-1 flex-col p-4 sm:p-5"><p className="text-sm font-medium text-[#6B7280]">{product.brand}</p><h3 className="mt-1 min-h-12 text-base font-semibold leading-6 text-[#111827]"><Link className={`rounded-sm hover:text-[#1D4ED8] ${focus}`} href={product.productHref} title={product.name}><span className="line-clamp-2">{product.name}</span></Link></h3><div className="mt-4"><p className="text-xs font-medium text-[#6B7280]">Current best price</p><p className="mt-1 text-xl font-bold text-[#111827]">{price}</p><p className="mt-1 text-sm text-[#6B7280]">Available at {product.storeCount} {product.storeCount === 1 ? "store" : "stores"}</p></div><div className="mt-auto grid grid-cols-[auto_1fr] gap-2 pt-5"><CompareButton productName={product.name} /><Link className={`flex min-h-11 items-center justify-center rounded-[10px] bg-[#2563EB] px-4 text-sm font-semibold text-white hover:bg-[#1D4ED8] ${focus}`} href={product.dealsHref}>View deals</Link></div></div>
 </article>;
}
