"use client";
/* eslint-disable @next/next/no-img-element -- Supabase bucket host is deployment-specific. */

import Link from "next/link";
import { useActionState, useRef, useState } from "react";
import { createGuide, updateGuide } from "@/app/admin/(protected)/knowledge-hub/actions";
import type { KnowledgeHubItem } from "@/lib/types/database";
import { initialGuideActionState, KNOWLEDGE_HUB_CATEGORIES, slugifyGuide, type GuideField } from "@/lib/validation/knowledge-hub";

const input = "mt-2 min-h-12 w-full rounded-[10px] border border-[#D1D5DB] bg-white px-4 text-base outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-[#2563EB] disabled:bg-[#F3F4F6]";
const size = (n: number) => `${(n / 1024 / 1024).toFixed(n >= 1024 * 1024 ? 1 : 2)} MB`;
export function KnowledgeHubForm({ item }: { item?: KnowledgeHubItem }) {
  const action = item ? updateGuide.bind(null, item.id) : createGuide; const [state, formAction, pending] = useActionState(action, initialGuideActionState);
  const [title, setTitle] = useState(item?.title ?? ""); const [slug, setSlug] = useState(item?.slug ?? ""); const [slugEdited, setSlugEdited] = useState(Boolean(item));
  const [pdf, setPdf] = useState<File | null>(null); const [removeThumbnail, setRemoveThumbnail] = useState(false); const [imagePreview, setImagePreview] = useState(item?.thumbnail_url ?? ""); const [pdfPreview, setPdfPreview] = useState(item?.pdf_url ?? ""); const pdfRef = useRef<HTMLInputElement>(null); const imageRef = useRef<HTMLInputElement>(null);
  const err = (f: GuideField) => state.fieldErrors[f] ? <p className="mt-2 text-sm font-medium text-[#B91C1C]" id={`${f}-error`}>{state.fieldErrors[f]}</p> : null;
  const aria = (f: GuideField) => ({ "aria-invalid": Boolean(state.fieldErrors[f]), "aria-describedby": state.fieldErrors[f] ? `${f}-error` : undefined });
  return <form action={formAction} className="mt-8 space-y-6 pb-24 sm:pb-0">
    {state.status === "error" ? <div className="rounded-[10px] border border-[#FCA5A5] bg-[#FEF2F2] px-4 py-3 text-sm font-medium text-[#991B1B]" role="alert">{state.message}</div> : null}
    <fieldset className="rounded-2xl border border-[#E5E7EB] bg-white p-5 sm:p-6"><legend className="px-1 text-lg font-bold">PDF guide</legend><div className="mt-2 space-y-3">
      <label className="text-sm font-semibold" htmlFor="guide-pdf">PDF file {item ? "(choose only to replace)" : ""}</label><input ref={pdfRef} {...aria("pdf")} accept="application/pdf,.pdf" className="sr-only" disabled={pending} id="guide-pdf" name="pdf" onChange={(e) => { const file = e.target.files?.[0] ?? null; setPdf(file); setPdfPreview(file ? URL.createObjectURL(file) : item?.pdf_url ?? ""); }} required={!item} type="file"/>
      <button className="flex min-h-28 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#93C5FD] bg-[#EFF6FF] p-4 text-center hover:border-[#2563EB]" disabled={pending} onClick={() => pdfRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); const file = e.dataTransfer.files[0]; if (!file || !pdfRef.current) return; const transfer = new DataTransfer(); transfer.items.add(file); pdfRef.current.files = transfer.files; setPdf(file); setPdfPreview(URL.createObjectURL(file)); }} type="button"><span className="font-semibold text-[#1D4ED8]">{pdf ? "Replace selected PDF" : item ? "Replace PDF" : "Choose or drop a PDF"}</span><span className="mt-1 text-sm text-[#6B7280]">Maximum 25 MB</span></button>
      {pdf ? <p className="break-all text-sm"><strong>{pdf.name}</strong> · {size(pdf.size)}</p> : item ? <p className="text-sm text-[#6B7280]">Current PDF · {size(item.pdf_size_bytes)}</p> : null}{err("pdf")}
      {pdfPreview ? <a className="inline-flex min-h-11 items-center font-semibold text-[#1D4ED8] underline" href={pdfPreview} rel="noopener noreferrer" target="_blank">Preview PDF</a> : null}
    </div></fieldset>
    <fieldset className="rounded-2xl border border-[#E5E7EB] bg-white p-5 sm:p-6"><legend className="px-1 text-lg font-bold">Guide details</legend><div className="mt-2 grid gap-6 md:grid-cols-2">
      <div><label className="text-sm font-semibold" htmlFor="guide-title">Title</label><input {...aria("title")} className={`${input} text-lg`} disabled={pending} id="guide-title" maxLength={200} name="title" onChange={(e) => { setTitle(e.target.value); if (!slugEdited) setSlug(slugifyGuide(e.target.value)); }} required value={title}/>{err("title")}</div>
      <div><label className="text-sm font-semibold" htmlFor="guide-slug">Slug</label><input {...aria("slug")} className={input} disabled={pending} id="guide-slug" maxLength={160} name="slug" onChange={(e) => { setSlugEdited(true); setSlug(slugifyGuide(e.target.value)); }} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required value={slug}/>{err("slug")}</div>
      <div className="md:col-span-2"><label className="text-sm font-semibold" htmlFor="guide-description">Short description</label><textarea {...aria("description")} className={`${input} min-h-32 py-3`} defaultValue={item?.description} disabled={pending} id="guide-description" maxLength={500} name="description" required/><p className="mt-2 text-xs text-[#6B7280]">Up to 500 characters. Explain what the visitor will learn.</p>{err("description")}</div>
      <div><label className="text-sm font-semibold" htmlFor="guide-category">Category</label><select {...aria("category")} className={input} defaultValue={item?.category ?? ""} disabled={pending} id="guide-category" name="category" required><option disabled value="">Choose a category</option>{KNOWLEDGE_HUB_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select>{err("category")}</div>
      <div><label className="text-sm font-semibold" htmlFor="guide-tags">Tags</label><input className={input} defaultValue={item?.tags.join(", ")} disabled={pending} id="guide-tags" name="tags" placeholder="laptops, buying tips"/><p className="mt-2 text-xs text-[#6B7280]">Separate tags with commas.</p></div>
      <div><label className="text-sm font-semibold" htmlFor="guide-author">Author name</label><input className={input} defaultValue={item?.author_name ?? ""} disabled={pending} id="guide-author" name="authorName"/></div>
    </div></fieldset>
    <fieldset className="rounded-2xl border border-[#E5E7EB] bg-white p-5 sm:p-6"><legend className="px-1 text-lg font-bold">Thumbnail (optional)</legend><input ref={imageRef} accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={pending} id="guide-thumbnail" name="thumbnail" onChange={(e) => { const file = e.target.files?.[0] ?? null; if (file) setImagePreview(URL.createObjectURL(file)); setRemoveThumbnail(false); }} type="file"/><input name="removeThumbnail" type="hidden" value={removeThumbnail ? "true" : "false"}/><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-center">
      {imagePreview && !removeThumbnail ? <img alt="Thumbnail preview" className="aspect-[16/9] w-full rounded-xl bg-[#F3F4F6] object-cover sm:w-64" src={imagePreview}/> : <div className="flex aspect-[16/9] w-full items-center justify-center rounded-xl bg-[#E5E7EB] text-sm text-[#6B7280] sm:w-64">HypeBuzz guide</div>}
      <div className="flex flex-wrap gap-3"><button className="min-h-11 rounded-[10px] border border-[#D1D5DB] px-4 font-semibold" disabled={pending} onClick={() => imageRef.current?.click()} type="button">{imagePreview && !removeThumbnail ? "Replace" : "Choose image"}</button>{imagePreview && !removeThumbnail ? <button className="min-h-11 rounded-[10px] border border-[#FCA5A5] px-4 font-semibold text-[#B91C1C]" disabled={pending} onClick={() => { setRemoveThumbnail(true); setImagePreview(""); if (imageRef.current) imageRef.current.value = ""; }} type="button">Remove</button> : null}</div>
    </div>{err("thumbnail")}</fieldset>
    <div className="fixed inset-x-0 bottom-0 z-30 flex gap-2 border-t border-[#E5E7EB] bg-white p-3 shadow-[0_-8px_24px_rgba(15,23,42,.08)] sm:static sm:justify-end sm:border-0 sm:bg-transparent sm:p-0 sm:shadow-none"><Link className="hidden min-h-12 items-center justify-center rounded-[10px] border border-[#D1D5DB] bg-white px-5 font-semibold sm:inline-flex" href="/admin/knowledge-hub">Cancel</Link><button className="min-h-12 flex-1 rounded-[10px] border border-[#2563EB] bg-white px-4 font-semibold text-[#1D4ED8] disabled:opacity-60 sm:flex-none" disabled={pending} name="intent" type="submit" value="draft">{pending ? "Saving…" : "Save Draft"}</button><button className="min-h-12 flex-1 rounded-[10px] bg-[#2563EB] px-5 font-semibold text-white disabled:bg-[#93C5FD] sm:flex-none" disabled={pending} name="intent" type="submit" value="publish">{pending ? "Publishing…" : "Publish"}</button></div>
  </form>;
}
