"use client";
import { useEffect, useState } from "react";
import Cropper, { type Area, type Point } from "react-easy-crop";
import { cropProductImage } from "@/lib/images/crop-image";

const presets=[{label:"Product square",value:1},{label:"Portrait",value:4/5},{label:"Landscape",value:4/3}] as const;
export function ProductImageEditor({file,sourceUrl,isPrimary,onCancel,onApply}:{file:File;sourceUrl:string;isPrimary:boolean;onCancel:()=>void;onApply:(file:File)=>void}){
  const [crop,setCrop]=useState<Point>({x:0,y:0});const[zoom,setZoom]=useState(1);const[rotation,setRotation]=useState(0);const[aspect,setAspect]=useState(1);const[originalAspect,setOriginalAspect]=useState(1);const[pixels,setPixels]=useState<Area|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";const image=new Image();image.onload=()=>setOriginalAspect(image.naturalWidth/image.naturalHeight);image.src=sourceUrl;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")onCancel();};window.addEventListener("keydown",escape);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",escape);};},[onCancel,sourceUrl]);
  function reset(){setCrop({x:0,y:0});setZoom(1);setRotation(0);setAspect(1);setError("");}
  async function apply(){if(!pixels)return;setBusy(true);setError("");try{onApply(await cropProductImage(file,sourceUrl,pixels,rotation));}catch{setError("The image could not be edited on this device. You can upload the original image or choose another file.");setBusy(false);}}
  return <div aria-labelledby="image-editor-title" aria-modal="true" className="fixed inset-0 z-[100] flex flex-col overflow-hidden bg-[#050A14] text-white" role="dialog"><header className="flex min-h-16 items-center justify-between border-b border-white/15 px-4"><div><h2 className="font-bold" id="image-editor-title">Edit product image</h2><p className="text-xs text-slate-300">Drag to reposition. Pinch or use the slider to zoom.</p></div><button className="min-h-11 rounded-[10px] border border-white/25 px-4 font-semibold" disabled={busy} onClick={onCancel} type="button">Cancel</button></header>
    <div className="relative min-h-0 flex-1 bg-black"><Cropper aspect={aspect} crop={crop} image={sourceUrl} maxZoom={4} minZoom={1} onCropChange={setCrop} onCropComplete={(_area,nextPixels)=>setPixels(nextPixels)} onRotationChange={setRotation} onZoomChange={setZoom} rotation={rotation} showGrid zoom={zoom}/>{isPrimary&&aspect===1?<div aria-hidden="true" className="pointer-events-none absolute inset-[18%] border border-dashed border-white/60"/>:null}</div>
    <div className="max-h-[45dvh] overflow-y-auto border-t border-white/15 bg-[#0A1224] p-4"><div className="mx-auto max-w-3xl space-y-4"><div><label className="text-sm font-semibold" htmlFor="crop-preset">Crop preset</label><select className="ml-3 min-h-11 rounded-[10px] bg-white px-3 text-[#111827]" id="crop-preset" onChange={event=>setAspect(Number(event.target.value))} value={aspect}><option value={1}>Product square (1:1)</option>{presets.slice(1).map(p=><option key={p.label} value={p.value}>{p.label}</option>)}<option value={originalAspect}>Original aspect</option></select>{isPrimary?<p className="mt-2 text-xs text-[#BFDBFE]">For the primary image, 1:1 is recommended. Keep the product inside the safe-area guide with some spacing.</p>:null}</div>
      <div><div className="flex justify-between text-sm"><label htmlFor="crop-zoom">Zoom</label><span>{zoom.toFixed(1)}×</span></div><input className="mt-2 h-11 w-full accent-[#2563EB]" id="crop-zoom" max="4" min="1" onChange={event=>setZoom(Number(event.target.value))} step="0.05" type="range" value={zoom}/></div>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><button className="min-h-12 rounded-[10px] border border-white/25 font-semibold" onClick={()=>setZoom(value=>Math.max(1,value-.2))} type="button">Zoom out</button><button className="min-h-12 rounded-[10px] border border-white/25 font-semibold" onClick={()=>setZoom(value=>Math.min(4,value+.2))} type="button">Zoom in</button><button className="min-h-12 rounded-[10px] border border-white/25 font-semibold" onClick={()=>setRotation(value=>value-90)} type="button">Rotate left</button><button className="min-h-12 rounded-[10px] border border-white/25 font-semibold" onClick={()=>setRotation(value=>value+90)} type="button">Rotate right</button></div>
      {error?<p className="rounded-[10px] bg-[#7F1D1D] p-3 text-sm" role="alert">{error}</p>:null}<div className="grid grid-cols-2 gap-3"><button className="min-h-12 rounded-[10px] border border-white/25 font-semibold" disabled={busy} onClick={reset} type="button">Reset</button><button className="min-h-12 rounded-[10px] bg-[#2563EB] font-bold disabled:bg-[#64748B]" disabled={busy||!pixels} onClick={apply} type="button">{busy?"Creating preview…":"Apply crop"}</button></div></div></div>
  </div>;
}
