"use client";
/* eslint-disable @next/next/no-img-element -- previews may use administrator-provided hosts. */
import { useRef, useState } from "react";
import { ProductImageEditor } from "./product-image-editor";

export type ProductImageValue = { id: string; imageUrl: string; sourceType: "upload" | "external"; isPrimary: boolean; sortOrder: number };
type Item = { key: string; kind: "existing" | "external" | "upload"; id?: string; url: string; originalUrl?: string; originalFile?: File; fileIndex?: number; name: string; size?: number; loadError?: boolean; edited?: boolean };
const formatSize = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;

export function ProductImagesField({ initialImages, disabled, error }: { initialImages: ProductImageValue[]; disabled: boolean; error?: string }) {
  const [items, setItems] = useState<Item[]>(initialImages.sort((a,b) => a.sortOrder-b.sortOrder).map(x => ({ key: x.id, kind: "existing", id: x.id, url: x.imageUrl, name: x.sourceType === "upload" ? "Uploaded image" : "External image" })));
  const initialPrimary = Math.max(0, initialImages.sort((a,b) => a.sortOrder-b.sortOrder).findIndex(x => x.isPrimary));
  const [primary, setPrimary] = useState(initialPrimary); const [url, setUrl] = useState(""); const [localError, setLocalError] = useState(""); const [editingIndex,setEditingIndex]=useState<number|null>(null); const inputRef = useRef<HTMLInputElement>(null); const filesRef = useRef<File[]>([]);
  const manifest = items.map((item, index) => ({ kind: item.kind, id: item.id, url: item.kind === "external" ? item.url : undefined, fileIndex: item.fileIndex, isPrimary: index === primary }));
  function remove(index: number) { const removed = items[index]; if (removed.kind === "upload" && removed.fileIndex !== undefined) { const removedFileIndex = removed.fileIndex; filesRef.current = filesRef.current.filter((_,i) => i !== removedFileIndex); const transfer = new DataTransfer(); filesRef.current.forEach(file => transfer.items.add(file)); if (inputRef.current) inputRef.current.files = transfer.files; setItems(current => current.filter((_,i) => i !== index).map(item => item.kind === "upload" && (item.fileIndex ?? 0) > removedFileIndex ? {...item,fileIndex:(item.fileIndex ?? 1)-1}:item)); } else setItems(current => current.filter((_,i) => i !== index)); setPrimary(current => current === index ? 0 : current > index ? current - 1 : current); }
  function move(index: number, delta: number) { const next = index + delta; if (next < 0 || next >= items.length) return; const copy = [...items]; [copy[index], copy[next]] = [copy[next], copy[index]]; setItems(copy); setPrimary(current => current === index ? next : current === next ? index : current); }
  function addUrl() { try { const parsed = new URL(url.trim()); if (!["http:","https:"].includes(parsed.protocol)) throw new Error(); if (items.length >= 8) return setLocalError("You can add up to 8 product images."); setItems(x => [...x, { key: crypto.randomUUID(), kind: "external", url: parsed.toString(), name: "External image" }]); setUrl(""); setLocalError(""); } catch { setLocalError("Enter a complete HTTP or HTTPS image URL."); } }
  function selectFiles(files: FileList | null) { if (!files) return; const accepted = Array.from(files); if (items.length + accepted.length > 8) return setLocalError("You can upload up to 8 product images."); if (accepted.some(f => !["image/jpeg","image/png","image/webp"].includes(f.type))) return setLocalError("Only JPG, PNG, or WebP images are allowed."); if (accepted.some(f => f.size > 5*1024*1024)) return setLocalError("Each image must be smaller than 5 MB."); const base = filesRef.current.length; filesRef.current = [...filesRef.current,...accepted]; const transfer = new DataTransfer(); filesRef.current.forEach(file => transfer.items.add(file)); if (inputRef.current) inputRef.current.files = transfer.files; setItems(x => [...x, ...accepted.map((file,i) => {const objectUrl=URL.createObjectURL(file);return { key: crypto.randomUUID(), kind: "upload" as const, url: objectUrl,originalUrl:objectUrl,originalFile:file, fileIndex: base+i, name: file.name, size: file.size };})]); setLocalError(""); }
  function applyEdit(index:number,file:File){const item=items[index];if(item.kind!=="upload"||item.fileIndex===undefined)return;filesRef.current[item.fileIndex]=file;const transfer=new DataTransfer();filesRef.current.forEach(value=>transfer.items.add(value));if(inputRef.current)inputRef.current.files=transfer.files;setItems(current=>current.map((value,i)=>i===index?{...value,url:URL.createObjectURL(file),name:file.name,size:file.size,edited:true}:value));setEditingIndex(null);}
  return <fieldset className="rounded-2xl border border-[#E5E7EB] bg-white p-5 shadow-[0_1px_2px_rgba(17,24,39,0.04)] sm:p-6"><legend className="px-1 text-lg font-bold">Product images</legend><p className="mt-2 text-sm text-[#6B7280]">Upload images, add external URLs, or use both. Maximum 8 images and 5 MB each.</p>
    <input name="imageManifest" type="hidden" value={JSON.stringify(manifest)}/>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><div><input ref={inputRef} accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={disabled} id="product-images" multiple name="uploadedImages" onChange={e => selectFiles(e.target.files)} type="file"/><input accept="image/jpeg,image/png,image/webp" capture="environment" className="sr-only" disabled={disabled} id="product-camera-image" onChange={e=>selectFiles(e.target.files)} type="file"/><div className="grid grid-cols-2 gap-2"><label className="flex min-h-14 cursor-pointer items-center justify-center rounded-[10px] border-2 border-dashed border-[#93C5FD] bg-[#EFF6FF] px-3 text-center font-semibold text-[#1D4ED8]" htmlFor="product-images">Choose images</label><label className="flex min-h-14 cursor-pointer items-center justify-center rounded-[10px] border border-[#93C5FD] px-3 text-center font-semibold text-[#1D4ED8]" htmlFor="product-camera-image">Use camera</label></div><p className="mt-2 text-xs text-[#6B7280]">Phone gallery, camera, or computer. JPG, PNG, or WebP.</p></div>
      <div><label className="text-sm font-semibold" htmlFor="product-image-url">Add image URL</label><div className="mt-2 flex gap-2"><input className="min-h-12 min-w-0 flex-1 rounded-[10px] border border-[#D1D5DB] px-3" disabled={disabled} id="product-image-url" onChange={e => setUrl(e.target.value)} placeholder="https://example.com/image.jpg" type="url" value={url}/><button className="min-h-12 rounded-[10px] border border-[#2563EB] px-4 font-semibold text-[#1D4ED8]" disabled={disabled || !url.trim()} onClick={addUrl} type="button">Add</button></div></div></div>
    {localError || error ? <p className="mt-3 text-sm font-medium text-[#B91C1C]" role="alert">{localError || error}</p> : null}
    {items.length ? <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.map((item,index) => <article className={`overflow-hidden rounded-xl border bg-white ${index === primary ? "border-[#2563EB] ring-2 ring-[#BFDBFE]" : "border-[#E5E7EB]"}`} key={item.key}><div className="relative aspect-square bg-[#F8FAFC]"><img alt={`Product image preview ${index+1}`} className="h-full w-full object-contain p-2" onError={(event) => { event.currentTarget.onerror=null; setItems(x => x.map(y => y.key === item.key ? {...y,loadError:true}:y)); }} src={item.url}/>{item.edited?<span className="absolute right-2 top-2 rounded-full bg-[#166534] px-2 py-1 text-[10px] font-bold text-white">Edited</span>:null}</div><div className="space-y-2 p-3"><p className="truncate text-xs font-semibold">{item.name}</p>{item.size ? <p className="text-xs text-[#6B7280]">{formatSize(item.size)}</p>:null}{item.loadError ? <p className="text-xs text-[#B91C1C]">Preview could not load.</p>:null}{item.kind==="upload"?<button className="min-h-10 w-full rounded border border-[#93C5FD] text-xs font-semibold text-[#1D4ED8]" disabled={disabled} onClick={()=>setEditingIndex(index)} type="button">Edit image</button>:null}<label className="flex min-h-10 cursor-pointer items-center gap-2 text-xs font-bold text-[#1D4ED8]"><input checked={index===primary} className="h-5 w-5" name="primaryPreview" onChange={() => setPrimary(index)} type="radio"/>Primary</label><div className="grid grid-cols-2 gap-1"><button aria-label={`Move image ${index+1} earlier`} className="min-h-10 rounded border" disabled={disabled||index===0} onClick={() => move(index,-1)} type="button">←</button><button aria-label={`Move image ${index+1} later`} className="min-h-10 rounded border" disabled={disabled||index===items.length-1} onClick={() => move(index,1)} type="button">→</button></div><button className="min-h-10 w-full rounded border border-[#FCA5A5] text-xs font-semibold text-[#B91C1C]" disabled={disabled} onClick={() => remove(index)} type="button">Remove</button></div></article>)}</div>:<p className="mt-5 rounded-xl bg-[#F8FAFC] p-5 text-center text-sm text-[#6B7280]">No images selected. Existing URL-only products can still be saved without images.</p>}
    {editingIndex!==null&&items[editingIndex]?.kind==="upload"&&items[editingIndex].originalFile?<ProductImageEditor file={items[editingIndex].originalFile} isPrimary={editingIndex===primary} onApply={file=>applyEdit(editingIndex,file)} onCancel={()=>setEditingIndex(null)} sourceUrl={items[editingIndex].originalUrl!}/>:null}
  </fieldset>;
}
