import type { Metadata } from "next";
import { CompanyCta } from "@/components/company/company-cta";
import { InformationHero } from "@/components/information/information-hero";
import { UiOnlyForm } from "@/components/information/ui-only-form";
import { supportEmail } from "@/lib/content/policy-constants";
import { absoluteUrl } from "@/lib/seo/site";
const description="Report potentially incorrect product, price, availability, merchant, or destination information displayed on HypeBuzz.";
export const metadata:Metadata={title:"Report Incorrect Information",description,alternates:{canonical:absoluteUrl("/report-information")},openGraph:{type:"website",title:"Report Incorrect Information | HypeBuzz",description,url:absoluteUrl("/report-information"),siteName:"HypeBuzz"},twitter:{card:"summary_large_image",title:"Report Incorrect Information | HypeBuzz",description}};
const fields=[{id:"product-name",label:"Product name",placeholder:"Name shown on HypeBuzz"},{id:"product-url",label:"Product URL",placeholder:"https://hypebuzz.in/products/...",type:"url" as const},{id:"merchant",label:"Merchant",placeholder:"Merchant connected to the issue"},{id:"issue-type",label:"Issue type",placeholder:"Select an issue",type:"select" as const,options:["Incorrect product information","Incorrect price or discount","Availability issue","Incorrect merchant information","Broken or unsafe destination","Other"]},{id:"description",label:"Description",placeholder:"Explain what appears incorrect and what you expected to see",type:"textarea" as const},{id:"evidence-url",label:"Optional evidence URL",placeholder:"https://...",type:"url" as const},{id:"contact-email",label:"Contact email",placeholder:"you@example.com",type:"email" as const,autoComplete:"email"}] as const;
export default function Page(){return <><InformationHero eyebrow="Support" introduction="Help HypeBuzz review product, price, availability, merchant, or link information that may be incomplete, outdated, or incorrect." title="Report Incorrect Information"/><section className="mx-auto max-w-[960px] px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="grid gap-8 lg:grid-cols-[0.65fr_1.35fr]"><div><h2 className="text-2xl font-bold text-[#111827]">What to report</h2><p className="mt-4 leading-7 text-[#4B5563]">Reports may concern product identity or specifications, displayed prices, discounts, availability, merchant attribution, broken destinations, or other information that could affect a shopping decision.</p><p className="mt-4 leading-7 text-[#4B5563]">The form does not currently transmit data. For review now, email <a className="font-semibold text-[#1D4ED8] underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2563EB]" href={`mailto:${supportEmail}`}>{supportEmail}</a> with the affected URL and supporting details.</p></div><div className="rounded-2xl border border-[#E5E7EB] bg-white p-6 sm:p-8"><h2 className="text-2xl font-bold text-[#111827]">Issue details</h2><p className="mt-3 mb-7 leading-7 text-[#4B5563]">Do not include passwords, payment information, or other sensitive personal data.</p><UiOnlyForm fields={fields} notice="Online submission functionality is being prepared."/></div></div></section><CompanyCta description="Review how HypeBuzz handles corrections or return to product search." secondaryHref="/accuracy-policy" secondaryLabel="Read the accuracy policy" title="Help improve information quality"/></>}
