/* eslint-disable @next/next/no-img-element -- Supabase bucket host is deployment-specific. */
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { GuideCard } from "@/components/knowledge-hub/guide-card";
import { Footer } from "@/components/layout/footer";
import { HomepageHeader } from "@/components/layout/homepage-header";
import { getPublishedGuide, getRelatedGuides } from "@/lib/data/knowledge-hub";
import { absoluteUrl } from "@/lib/seo/site";
const date = (v: string | null) => v ? new Intl.DateTimeFormat("en-IN", { dateStyle: "long" }).format(new Date(v)) : ""; const size = (n: number) => `${(n / 1024 / 1024).toFixed(1)} MB`;
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const guide = await getPublishedGuide(slug); if (!guide) return { title: "Guide not found", robots: { index: false, follow: false } }; const url = absoluteUrl(`/knowledge-hub/${guide.slug}`); return { title: guide.title, description: guide.description, alternates: { canonical: url }, openGraph: { type: "article", title: guide.title, description: guide.description, url, images: [guide.thumbnail_url ?? absoluteUrl("/brand/hypebuzz-banner-v3.png")] } }; }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const guide = await getPublishedGuide(slug); if (!guide) notFound(); const related = await getRelatedGuides(guide); return <><HomepageHeader/><main className="bg-[#F8FAFC] px-4 py-10 sm:py-14" id="main-content"><article className="mx-auto max-w-4xl"><nav aria-label="Breadcrumb" className="text-sm text-[#6B7280]"><Link className="hover:text-[#1D4ED8]" href="/knowledge-hub">Knowledge Hub</Link> <span aria-hidden="true">/</span> <span>{guide.title}</span></nav><div className="mt-6 overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white"><div className="aspect-[16/9] max-h-[30rem] bg-[#E5E7EB]">{guide.thumbnail_url ? <img alt="" className="h-full w-full object-cover" src={guide.thumbnail_url}/> : <div className="flex h-full items-center justify-center bg-gradient-to-br from-[#DBEAFE] to-[#E5E7EB] text-2xl font-bold text-[#1D4ED8]">HypeBuzz PDF Guide</div>}</div><div className="p-5 sm:p-8"><p className="text-sm font-bold uppercase tracking-wider text-[#2563EB]">{guide.category}</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-5xl">{guide.title}</h1><p className="mt-5 text-lg leading-8 text-[#4B5563]">{guide.description}</p><dl className="mt-6 grid gap-3 text-sm text-[#6B7280] sm:grid-cols-3"><div><dt className="font-semibold text-[#111827]">Published</dt><dd>{date(guide.published_at)}</dd></div><div><dt className="font-semibold text-[#111827]">Author</dt><dd>{guide.author_name || "HypeBuzz Editorial"}</dd></div><div><dt className="font-semibold text-[#111827]">File</dt><dd>PDF · {size(guide.pdf_size_bytes)}</dd></div></dl>{guide.tags.length ? <div className="mt-6 flex flex-wrap gap-2">{guide.tags.map(t => <span className="rounded-full bg-[#EFF6FF] px-3 py-1 text-sm text-[#1D4ED8]" key={t}>{t}</span>)}</div> : null}<div className="mt-8 grid gap-3 sm:grid-cols-2"><a className="inline-flex min-h-12 items-center justify-center rounded-[10px] bg-[#2563EB] px-5 font-semibold text-white" href={guide.pdf_url} rel="noopener noreferrer" target="_blank">View PDF</a><a className="inline-flex min-h-12 items-center justify-center rounded-[10px] border border-[#D1D5DB] px-5 font-semibold" download href={guide.pdf_url}>Download PDF</a></div></div></div></article>{related.length ? <section className="mx-auto mt-12 max-w-7xl"><h2 className="text-2xl font-bold">Related guides</h2><div className="mt-5 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{related.map(g => <GuideCard guide={g} key={g.id}/>)}</div></section> : null}</main><Footer/></>; }
